// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

import 'package:fish_serializable/serializable.dart';
import 'package:meta/meta.dart';
import 'WellnessDOS.dart';

class Main implements FishSerializable {
  String success;

  List<WellnessDOS> wellnessDOS;

  Main({
    this.success,
    this.wellnessDOS,
  });

  Main.serializableCreator(ValueHolder holder) : 
    success = holder.readString(key: 'success'),
    wellnessDOS = holder.readList<WellnessDOS, WellnessDOS>(
      key: 'wellnessDOS',
      creator: WellnessDOS.staticCreator
    );

  static Main staticCreator(ValueHolder holder) => 
    Main.serializableCreator(holder);

  @override
  Creator<Main> get creator => staticCreator;

  @override
  void writeTo(ValueHolder holder) {
    holder.writeString(key: 'success', val: success);
    holder.writeList(key: 'wellnessDOS', val: wellnessDOS);
  }
}