// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

import 'package:fish_serializable/serializable.dart';
import 'package:meta/meta.dart';
import 'Benefits.dart';

class WellnessDOS implements FishSerializable {
  List<Benefits> benefits;

  String canBuy;

  String dateTime;

  String serverTime;

  String startTime;

  WellnessDOS({
    this.benefits,
    this.canBuy,
    this.dateTime,
    this.serverTime,
    this.startTime,
  });

  WellnessDOS.serializableCreator(ValueHolder holder) : 
    benefits = holder.readList<Benefits, Benefits>(
      key: 'benefits',
      creator: Benefits.staticCreator
    ),
    canBuy = holder.readString(key: 'canBuy'),
    dateTime = holder.readString(key: 'dateTime'),
    serverTime = holder.readString(key: 'serverTime'),
    startTime = holder.readString(key: 'startTime');

  static WellnessDOS staticCreator(ValueHolder holder) => 
    WellnessDOS.serializableCreator(holder);

  @override
  Creator<WellnessDOS> get creator => staticCreator;

  @override
  void writeTo(ValueHolder holder) {
    holder.writeList(key: 'benefits', val: benefits);
    holder.writeString(key: 'canBuy', val: canBuy);
    holder.writeString(key: 'dateTime', val: dateTime);
    holder.writeString(key: 'serverTime', val: serverTime);
    holder.writeString(key: 'startTime', val: startTime);
  }
}